### PR TITLE
Prepare for 5.x release

### PR DESCRIPTION
**Pull request by nocive**

### CODE REVIEW

**Comment by nocive** [comment]
@norberttech any other TODOs left? We have this version running in production ;)

**Comment by norberttech** [comment]
Look to me that we are ready to go! Let me release 5.x in a sec :)

**Comment by norberttech** [comment]
Thank you @nocive for all of your work, without it there would be no [5.0.0](https://github.com/norberttech/aceeditor-bundle/releases/tag/5.0.0) release, awesome job!!! 🎉🚀

**Comment by nocive** [comment]
@norberttech no problem, glad I could give back somehow :smile: :rocket: 

In other notes, you closed this PR but wouldn't it make sense to update the documentation accordingly?
The current install instructions mention 5.x-dev, rather than ^5.0.

It would also be nice to provide a compatibility matrix table for "php version / aceeditor-bundle version / symfony version", instead of this rather confusing section: https://github.com/norberttech/aceeditor-bundle/blob/5.x/README.md#symfony.

**Comment by norberttech** [comment]
yeah, good points, also an UPGRADE.md file that would explain how to upgrade from 4.x into 5.x would be nice to have

**Pull request closed without merging**
