### PR TITLE
Update the bundle

### PR DESCRIPTION
**Pull request by azzra**
Hello @norzechowicz 

I know this PR won't be merged as it, I've opened it for the discussion.

It looks like the bundle please people but it's hard to get it up to date (#6, #15 , #13, ...).
Lots of people made a fork but no one succeed to made it official.

So here is my fork for updating the bundle & with some tooling added (CI, unit tests, code coverage).
If you still don't have enough time to manage the bundle, I'll continue to manage my fork and put it on packagist for other projects, otherwise I'll be happy to change the namespace back and contribute here!

Let me know please.

Thanks.

### CODE REVIEW

**Comment by norzechowicz** [comment]
Hey, sorry I have no time to work on that on my own : ( Could you please give me at least list of changes that are required to make this bundle usable again? Maybe I'll try to figure out something next weekend, thanks!

**Comment by azzra** [comment]
Thanks for your answer.

I've already make changes for this bundle to be compatible with newer versions. You just have to review the code or if you don't have time, just let me know and I'll maintain a fork.
Fork is here: https://github.com/azzra/aceeditor-bundle

Main thing is I removed the Ace distribution from the bundle, we got enough frontend tools managing to handle this point and explain in the README how to get Ace on your own.

I've changed the namespace as well to be ready to maintain my own fork but if you're able to recover some time to manage your bundle I can revert this, of course.

**Comment by norzechowicz** [comment]
I can't merge this PR because:
1. you change namespaces so everything will break if somebody is using older version and migration might be problematic 
2. removing Ace from bundle (it was a mistake to put it here at the first place) is also a BC break

Second point is less problematic because we have 0.1.x released already so we can make master a new 1.0 but first I would like to prepare a list of things that needs to be done before releasing 1.0.0

**Comment by azzra** [comment]
I knew this PR won't be merged, I said it when opening it :)

PR with the original namespace is here #18, so let's continue over there.

Closing this one as it's purpose is over.

**Pull request closed without merging**
