### PR TITLE
Update compatibility matrix & install instructions

### PR DESCRIPTION
**Pull request by nocive**

### CODE REVIEW

**Comment by nocive** [comment]
@norberttech just addressing the install instructions here, I'd leave the UPGRADE guide to address separately.

Also, I'm not sure about the true compatibility with PHP versions for some of the older bundle versions, since the php version constraint is too relaxed (>=5.6).

**Comment by norberttech** [comment]
> Also, I'm not sure about the true compatibility with PHP versions for some of the older bundle versions, since the php version constraint is too relaxed (>=5.6).

I don't think we should support/expose anything that is not currently supported by symfony, meaning that whatever version of this bundle works with unsupported version of symfony should not be supported by us

**Comment by nocive** [comment]
So you're arguing to not include those versions at all in the compat matrix? I'm also fine with that option, just thought it would be nice to have this here for posterity, since the default branch people land on the repo is 5.x.

**Comment by norberttech** [comment]
Yeah, I would not put into the matrix anything that shoild not be supported, less maintenance is always better 😊

**Comment by nocive** [comment]
:+1: updated

**Pull request merged**
